#!/usr/bin/env node
/* validate_pqclean_kat.js — Cross-validation against PQClean Falcon-1024.
 *
 * Loads 100 (pk, msg, sm) triplets generated by PQClean (the audited
 * derivative of the official NIST round 3 Falcon submission) and runs
 * each through this codebase's pure-JS verifyRaw.
 *
 * Format: JSON array of { pk_hex, msg_hex, sm_hex, mlen }
 * Where:
 *   pk_hex = 1793 bytes (header 0x0A + modq-encoded h, n=1024)
 *   sm_hex = DETACHED: header(0x3A) + nonce(40) + sig_compressed
 *   msg_hex = mlen bytes of the message
 *
 * The vectors here were generated using:
 *   from pqcrypto.sign.falcon_1024 import generate_keypair, sign
 * (pqcrypto Python package, version 0.4.0, which wraps PQClean Falcon-1024
 *  CLEAN reference implementation, derived from the NIST round 3 submission).
 */
'use strict';
const fs = require('fs');
const path = require('path');
const { verifyRaw, hashToPoint, N } = require('../falcon1024-verify');
const { modqDecode, compDecode } = require('../falcon1024-kat-verify');

function polyToBuf(p) {
    const o = Buffer.alloc(2*N);
    for (let i = 0; i < N; i++) o.writeUInt16LE(p[i], 2*i);
    return o;
}
function sigToBuf(s) {
    const o = Buffer.alloc(2*N);
    for (let i = 0; i < N; i++) o.writeInt16LE(s[i], 2*i);
    return o;
}

const filePath = process.argv[2] || path.join(__dirname, 'pqclean_falcon1024_100.json');
const vectors = JSON.parse(fs.readFileSync(filePath));
console.log(`═══ PQClean Falcon-1024 cross-validation ═══`);
console.log(`File: ${filePath}`);
console.log(`Vectors: ${vectors.length}\n`);

let pass = 0, fail = 0;
const failures = [];
const t0 = Date.now();
for (let i = 0; i < vectors.length; i++) {
    const v = vectors[i];
    const pk = Buffer.from(v.pk_hex, 'hex');
    const msg = Buffer.from(v.msg_hex, 'hex');
    const sm = Buffer.from(v.sm_hex, 'hex');

    if (pk.length !== 1793 || pk[0] !== 0x0A) {
        failures.push({ i, reason: `bad pk header/length` });
        fail++; continue;
    }
    if (sm.length < 41 || sm[0] !== 0x3A) {
        failures.push({ i, reason: `bad sm header/length` });
        fail++; continue;
    }

    const h = modqDecode(pk.slice(1, 1 + 1792));
    const nonce = sm.slice(1, 41);
    const sigCompressed = sm.slice(41);

    let sigPoly;
    try {
        sigPoly = compDecode(sigCompressed).sig;
    } catch (e) {
        failures.push({ i, reason: `comp_decode: ${e.message}` });
        fail++; continue;
    }

    const hm = hashToPoint(nonce, msg);
    const ok = verifyRaw(hm, sigToBuf(sigPoly), polyToBuf(h));
    if (ok) pass++;
    else { fail++; failures.push({ i, reason: 'verify_raw rejected' }); }

    if ((i + 1) % 25 === 0) process.stdout.write(`  ${i+1}/${vectors.length}\r`);
}
const elapsed = ((Date.now() - t0) / 1000).toFixed(1);
process.stdout.write(' '.repeat(40) + '\r');
console.log(`Done in ${elapsed}s.`);
console.log(`  ✅ pass: ${pass}/${vectors.length}`);
console.log(`  ❌ fail: ${fail}/${vectors.length}`);
if (failures.length > 0 && failures.length <= 10) {
    console.log('Failures:');
    for (const f of failures) console.log(`  vec ${f.i}: ${f.reason}`);
}
if (fail === 0) {
    console.log('\n═══ ✅ ALL VECTORS PASSED ═══');
    console.log('   JS verify is byte-conformant with the PQClean reference.');
}
process.exit(fail === 0 ? 0 : 1);
